FROM node:10.15-alpine AS node_base

FROM node_base as deps
WORKDIR /home/node/app
COPY package.json /home/node/app/package.json
RUN npm install && npm cache clean --force

FROM node_base as build
WORKDIR /home/node/app
COPY --from=deps /home/node/app/node_modules /home/node/app/node_modules
COPY . /home/node/app
RUN npm build

FROM scratch AS ui
COPY --from=build /home/node/app/dist /home/node/app


# FROM node:10.15-jessie

# # Override in docker-compose
# ARG NODE_ENV=development
# ENV NODE_ENV $NODE_ENV

# # default to port 3000 for node, and 9229 and 9230 (tests) for debug
# ARG PORT=8000
# ENV PORT $PORT
# EXPOSE $PORT 9229 9230

# RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

# WORKDIR /home/node/app

# COPY package.json .

# RUN npm install && npm cache clean --force

# # copy in our source code last, as it changes the most
# COPY . .

# COPY --chown=node:node . .

# # the official node image provides an unprivileged user as a security best practice
# # https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
# USER node

# CMD [ "npm", "run", "dev:start" ]